# Generated by Django 4.2.2 on 2023-06-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencia',
            name='id_jurisprudencia',
            field=models.IntegerField(),
        ),
    ]
