# Generated by Django 4.2.2 on 2023-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_alter_jurisprudencia_descriptores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='valor',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
