# Generated by Django 4.2.2 on 2023-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_alter_valores_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='idItemlista',
            field=models.IntegerField(null=True),
        ),
    ]
