# Generated by Django 4.2.2 on 2023-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_alter_valores_iditemlista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='idParametro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='valores',
            name='item',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valores',
            name='parametro',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
