# Generated by Django 4.2.2 on 2023-06-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_concesion', models.CharField(max_length=145)),
                ('tipo_concesion', models.CharField(max_length=145)),
                ('comuna', models.CharField(max_length=145)),
                ('lugar', models.CharField(max_length=145)),
                ('n_rd', models.CharField(max_length=145)),
                ('tipo_tramite', models.CharField(max_length=145)),
                ('concesionario', models.CharField(max_length=255)),
                ('tipo_vigencia', models.CharField(max_length=145)),
            ],
        ),
    ]
