# Generated by Django 4.2.2 on 2023-06-21 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jurisprudencia', models.IntegerField(default=None)),
                ('tipoCausa', models.CharField(max_length=3)),
                ('rol', models.CharField(max_length=140)),
                ('caratula', models.CharField(max_length=140)),
                ('nombreProyecto', models.CharField(max_length=140)),
                ('fechaSentencia', models.CharField(max_length=140)),
                ('descriptores', models.CharField(max_length=255)),
                ('linkSentencia', models.CharField(max_length=255)),
                ('urlSentencia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('tribunal', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('relacionada', models.CharField(max_length=140)),
                ('visitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParametro', models.IntegerField()),
                ('idItemlista', models.IntegerField()),
                ('valor', models.CharField(max_length=140)),
                ('parametro', models.CharField(max_length=140)),
                ('item', models.CharField(max_length=140)),
                ('idjurisprudencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='scrapper.jurisprudencia', verbose_name='jurisprudencia')),
            ],
        ),
    ]
