# Generated by Django 4.2.2 on 2023-06-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_jurisprudencia_id_jurisprudencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores',
            name='id_valor',
            field=models.IntegerField(default=None),
        ),
    ]
