# Generated by Django 4.2.2 on 2023-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_valores_id_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencia',
            name='caratula',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='fechaSentencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='nombreProyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='relacionada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='rol',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='tribunal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valores',
            name='item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valores',
            name='parametro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valor',
            field=models.CharField(max_length=255),
        ),
    ]
