# Generated by Django 4.2.2 on 2023-06-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_alter_jurisprudencia_caratula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencia',
            name='descriptores',
            field=models.TextField(),
        ),
    ]
