# Generated by Django 4.2.2 on 2023-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_alter_valores_idparametro_alter_valores_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='valor',
            field=models.TextField(null=True),
        ),
    ]
